properly model dependencies between packages
`smt_launch_gazebo` doesn't depend directly on gazebo anymore, instead
it includes the launch file from `smt_model_description` which then
launches gazebo.

this is relevant when using `rosdep install --from-paths .` (though it
won't be able to download our packages if they were missing as they
aren't published, but it'd complain if one of them were forgotten from
the workspace), the error will then look like this:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
smt_launch_gazebo: Cannot locate rosdep definition for [smt_model_description]
```